version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      frontend:
        patterns:
          - "next"
          - "next-auth"
          - "wagmi"
          - "@rainbow-me/*"
          - "@tailwindcss/*"

  - package-ecosystem: "cargo"
    directory: "/apps/stellar_contracts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
